# Generated by Django 5.2.9 on 2025-12-23 20:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supabase_user_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('company', models.CharField(choices=[('Dko', 'Dko'), ('Mv', 'Mv')], max_length=50)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Comercial', 'Comercial'), ('Tienda', 'Tienda')], max_length=50)),
                ('can_view_reports', models.BooleanField(default=True)),
                ('can_view_user_management', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users_userprofile',
                'ordering': ['-created_at'],
            },
        ),
    ]
