# Generated by Django 5.2.9 on 2025-12-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('s3_key', models.CharField(help_text='Path to the file in S3', max_length=1024)),
                ('company', models.CharField(choices=[('Dko', 'Dko'), ('Mv', 'Mv')], max_length=50)),
                ('role_required', models.CharField(choices=[('Admin', 'Admin'), ('Comercial', 'Comercial'), ('Tienda', 'Tienda')], default='Tienda', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
