# Generated by Django 5.2.9 on 2025-12-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name for this category (e.g. 'Ventas')", max_length=255)),
                ('s3_prefix', models.CharField(help_text="Folder path in S3 (e.g. 'dkohome/Ventas/'). Must end with /", max_length=1024)),
                ('company', models.CharField(choices=[('Dko', 'Dko'), ('Mv', 'Mv')], max_length=50)),
                ('role_required', models.CharField(choices=[('Admin', 'Admin'), ('Comercial', 'Comercial'), ('Tienda', 'Tienda')], default='Tienda', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
