# Generated by Django 5.2.9 on 2026-01-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_can_view_closing_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_view_commission',
            field=models.BooleanField(default=False),
        ),
    ]
